<?php

return [
    'name' => 'Ecommerce',
    'SHOPEE_PARTNER_ID' => env('SHOPEE_PARTNER_ID'),
    'SHOPEE_PARTNER_SECRET' => env('SHOPEE_PARTNER_SECRET'),
    'SHOPEE_API_URL' => env('SHOPEE_API_URL'),
    'LAZADA_PARTNER_ID' => env('LAZADA_PARTNER_ID'),
    'LAZADA_PARTNER_SECRET' => env('LAZADA_PARTNER_SECRET'),
    'LAZADA_API_URL' => env('LAZADA_API_URL'),
    'LAZADA_AUTH_URL' => env('LAZADA_AUTH_URL'),
];
